apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gateway-ingress
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`route-api.ddns.net`)
      kind: Rule
      services:
        - name: gateway
          port: 3000
  tls:
    certResolver: letsencrypt